/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ClawWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "FEE_BASIS_POINTS"
      | "WELCOME_POINTS"
      | "balances"
      | "createWallet"
      | "deposit"
      | "depositToken"
      | "getAgentId"
      | "getTokenBalance"
      | "getWallet"
      | "owner"
      | "send"
      | "sendToAgent"
      | "sendToken"
      | "setTreasury"
      | "tokenBalances"
      | "totalAgents"
      | "transferOwnership"
      | "treasury"
      | "wallets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentToAgent"
      | "Deposit"
      | "PointsEarned"
      | "Sent"
      | "TokenDeposit"
      | "TokenSent"
      | "WalletCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WELCOME_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "balances", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "createWallet",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAgentId", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTokenBalance",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWallet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendToAgent",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendToken",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBalances",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "wallets", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WELCOME_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgentId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendToAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wallets", data: BytesLike): Result;
}

export namespace AgentToAgentEvent {
  export type InputTuple = [
    from: BytesLike,
    to: BytesLike,
    amount: BigNumberish,
    fee: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    fee: bigint,
    points: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    fee: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [agentId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [agentId: string, amount: bigint];
  export interface OutputObject {
    agentId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsEarnedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    points: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [agentId: string, points: bigint, reason: string];
  export interface OutputObject {
    agentId: string;
    points: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SentEvent {
  export type InputTuple = [
    from: BytesLike,
    to: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    fee: bigint,
    points: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    fee: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDepositEvent {
  export type InputTuple = [
    agentId: BytesLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [agentId: string, token: string, amount: bigint];
  export interface OutputObject {
    agentId: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSentEvent {
  export type InputTuple = [
    from: BytesLike,
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    token: string,
    amount: bigint,
    fee: bigint,
    points: bigint
  ];
  export interface OutputObject {
    from: string;
    to: string;
    token: string;
    amount: bigint;
    fee: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletCreatedEvent {
  export type InputTuple = [
    agentId: BytesLike,
    agentName: string,
    points: BigNumberish
  ];
  export type OutputTuple = [
    agentId: string,
    agentName: string,
    points: bigint
  ];
  export interface OutputObject {
    agentId: string;
    agentName: string;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClawWallet extends BaseContract {
  connect(runner?: ContractRunner | null): ClawWallet;
  waitForDeployment(): Promise<this>;

  interface: ClawWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  FEE_BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  WELCOME_POINTS: TypedContractMethod<[], [bigint], "view">;

  balances: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  createWallet: TypedContractMethod<
    [agentName: string],
    [string],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[agentId: BytesLike], [void], "payable">;

  depositToken: TypedContractMethod<
    [agentId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAgentId: TypedContractMethod<[agentName: string], [string], "view">;

  getTokenBalance: TypedContractMethod<
    [agentId: BytesLike, token: AddressLike],
    [bigint],
    "view"
  >;

  getWallet: TypedContractMethod<
    [agentId: BytesLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint] & {
        exists: boolean;
        balance: bigint;
        points: bigint;
        totalSent: bigint;
        totalReceived: bigint;
        txCount: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  send: TypedContractMethod<
    [agentId: BytesLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sendToAgent: TypedContractMethod<
    [fromAgentId: BytesLike, toAgentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sendToken: TypedContractMethod<
    [
      agentId: BytesLike,
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  tokenBalances: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  wallets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        exists: boolean;
        points: bigint;
        totalSent: bigint;
        totalReceived: bigint;
        txCount: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WELCOME_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createWallet"
  ): TypedContractMethod<[agentName: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[agentId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [agentId: BytesLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentId"
  ): TypedContractMethod<[agentName: string], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenBalance"
  ): TypedContractMethod<
    [agentId: BytesLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWallet"
  ): TypedContractMethod<
    [agentId: BytesLike],
    [
      [boolean, bigint, bigint, bigint, bigint, bigint] & {
        exists: boolean;
        balance: bigint;
        points: bigint;
        totalSent: bigint;
        totalReceived: bigint;
        txCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "send"
  ): TypedContractMethod<
    [agentId: BytesLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendToAgent"
  ): TypedContractMethod<
    [fromAgentId: BytesLike, toAgentId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendToken"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenBalances"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wallets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        exists: boolean;
        points: bigint;
        totalSent: bigint;
        totalReceived: bigint;
        txCount: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AgentToAgent"
  ): TypedContractEvent<
    AgentToAgentEvent.InputTuple,
    AgentToAgentEvent.OutputTuple,
    AgentToAgentEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "PointsEarned"
  ): TypedContractEvent<
    PointsEarnedEvent.InputTuple,
    PointsEarnedEvent.OutputTuple,
    PointsEarnedEvent.OutputObject
  >;
  getEvent(
    key: "Sent"
  ): TypedContractEvent<
    SentEvent.InputTuple,
    SentEvent.OutputTuple,
    SentEvent.OutputObject
  >;
  getEvent(
    key: "TokenDeposit"
  ): TypedContractEvent<
    TokenDepositEvent.InputTuple,
    TokenDepositEvent.OutputTuple,
    TokenDepositEvent.OutputObject
  >;
  getEvent(
    key: "TokenSent"
  ): TypedContractEvent<
    TokenSentEvent.InputTuple,
    TokenSentEvent.OutputTuple,
    TokenSentEvent.OutputObject
  >;
  getEvent(
    key: "WalletCreated"
  ): TypedContractEvent<
    WalletCreatedEvent.InputTuple,
    WalletCreatedEvent.OutputTuple,
    WalletCreatedEvent.OutputObject
  >;

  filters: {
    "AgentToAgent(bytes32,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      AgentToAgentEvent.InputTuple,
      AgentToAgentEvent.OutputTuple,
      AgentToAgentEvent.OutputObject
    >;
    AgentToAgent: TypedContractEvent<
      AgentToAgentEvent.InputTuple,
      AgentToAgentEvent.OutputTuple,
      AgentToAgentEvent.OutputObject
    >;

    "Deposit(bytes32,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "PointsEarned(bytes32,uint256,string)": TypedContractEvent<
      PointsEarnedEvent.InputTuple,
      PointsEarnedEvent.OutputTuple,
      PointsEarnedEvent.OutputObject
    >;
    PointsEarned: TypedContractEvent<
      PointsEarnedEvent.InputTuple,
      PointsEarnedEvent.OutputTuple,
      PointsEarnedEvent.OutputObject
    >;

    "Sent(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      SentEvent.InputTuple,
      SentEvent.OutputTuple,
      SentEvent.OutputObject
    >;
    Sent: TypedContractEvent<
      SentEvent.InputTuple,
      SentEvent.OutputTuple,
      SentEvent.OutputObject
    >;

    "TokenDeposit(bytes32,address,uint256)": TypedContractEvent<
      TokenDepositEvent.InputTuple,
      TokenDepositEvent.OutputTuple,
      TokenDepositEvent.OutputObject
    >;
    TokenDeposit: TypedContractEvent<
      TokenDepositEvent.InputTuple,
      TokenDepositEvent.OutputTuple,
      TokenDepositEvent.OutputObject
    >;

    "TokenSent(bytes32,address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokenSentEvent.InputTuple,
      TokenSentEvent.OutputTuple,
      TokenSentEvent.OutputObject
    >;
    TokenSent: TypedContractEvent<
      TokenSentEvent.InputTuple,
      TokenSentEvent.OutputTuple,
      TokenSentEvent.OutputObject
    >;

    "WalletCreated(bytes32,string,uint256)": TypedContractEvent<
      WalletCreatedEvent.InputTuple,
      WalletCreatedEvent.OutputTuple,
      WalletCreatedEvent.OutputObject
    >;
    WalletCreated: TypedContractEvent<
      WalletCreatedEvent.InputTuple,
      WalletCreatedEvent.OutputTuple,
      WalletCreatedEvent.OutputObject
    >;
  };
}
